# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{brianjlandau-sdoc-helpers}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Wanstrath", "Brian Landau"]
  s.date = %q{2011-11-19}
  s.description = %q{Simple helpers to make using sdoc easier.}
  s.email = %q{chris@ozmm.org}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "Rakefile",
    "brianjlandau-sdoc-helpers.gemspec",
    "lib/rake/sdoctask.rb",
    "lib/sdoc_helpers.rb",
    "lib/sdoc_helpers/markdown.rb",
    "lib/sdoc_helpers/pages.rb",
    "lib/sdoc_helpers/version.rb",
    "sdoc-helpers.gemspec"
  ]
  s.homepage = %q{http://github.com/brianjlandau/sdoc-helpers}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple helpers to make using sdoc easier.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

